// Code generated by mockery v2.15.0. DO NOT EDIT.

package usecasemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	entity "github.com/winartodev/go-pokedex/entity"
)

// PokemonUsecaseItf is an autogenerated mock type for the PokemonUsecaseItf type
type PokemonUsecaseItf struct {
	mock.Mock
}

// CatchPokemon provides a mock function with given fields: ctx, id
func (_m *PokemonUsecaseItf) CatchPokemon(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePokemon provides a mock function with given fields: ctx, data
func (_m *PokemonUsecaseItf) CreatePokemon(ctx context.Context, data entity.Pokemon) (int64, error) {
	ret := _m.Called(ctx, data)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, entity.Pokemon) int64); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, entity.Pokemon) error); ok {
		r1 = rf(ctx, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePokemon provides a mock function with given fields: ctx, id
func (_m *PokemonUsecaseItf) DeletePokemon(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllPokemon provides a mock function with given fields: ctx
func (_m *PokemonUsecaseItf) GetAllPokemon(ctx context.Context) ([]entity.PokemonList, error) {
	ret := _m.Called(ctx)

	var r0 []entity.PokemonList
	if rf, ok := ret.Get(0).(func(context.Context) []entity.PokemonList); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PokemonList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPokemonByFilter provides a mock function with given fields: ctx, filter
func (_m *PokemonUsecaseItf) GetAllPokemonByFilter(ctx context.Context, filter map[string]string) ([]entity.PokemonList, error) {
	ret := _m.Called(ctx, filter)

	var r0 []entity.PokemonList
	if rf, ok := ret.Get(0).(func(context.Context, map[string]string) []entity.PokemonList); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PokemonList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, map[string]string) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPokemonByID provides a mock function with given fields: ctx, id
func (_m *PokemonUsecaseItf) GetPokemonByID(ctx context.Context, id int64) (*entity.PokemonDetail, error) {
	ret := _m.Called(ctx, id)

	var r0 *entity.PokemonDetail
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.PokemonDetail); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PokemonDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePokemon provides a mock function with given fields: ctx, id, data
func (_m *PokemonUsecaseItf) UpdatePokemon(ctx context.Context, id int64, data entity.Pokemon) (*entity.PokemonDetail, error) {
	ret := _m.Called(ctx, id, data)

	var r0 *entity.PokemonDetail
	if rf, ok := ret.Get(0).(func(context.Context, int64, entity.Pokemon) *entity.PokemonDetail); ok {
		r0 = rf(ctx, id, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PokemonDetail)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, entity.Pokemon) error); ok {
		r1 = rf(ctx, id, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewPokemonUsecaseItf interface {
	mock.TestingT
	Cleanup(func())
}

// NewPokemonUsecaseItf creates a new instance of PokemonUsecaseItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPokemonUsecaseItf(t mockConstructorTestingTNewPokemonUsecaseItf) *PokemonUsecaseItf {
	mock := &PokemonUsecaseItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
