// Code generated by mockery v2.15.0. DO NOT EDIT.

package usecasemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserUsecaseItf is an autogenerated mock type for the UserUsecaseItf type
type UserUsecaseItf struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, username, password
func (_m *UserUsecaseItf) Login(ctx context.Context, username string, password string) (string, error) {
	ret := _m.Called(ctx, username, password)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, username, email, password, role
func (_m *UserUsecaseItf) Register(ctx context.Context, username string, email string, password string, role int64) (int64, error) {
	ret := _m.Called(ctx, username, email, password, role)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int64) int64); ok {
		r0 = rf(ctx, username, email, password, role)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int64) error); ok {
		r1 = rf(ctx, username, email, password, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserUsecaseItf interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserUsecaseItf creates a new instance of UserUsecaseItf. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserUsecaseItf(t mockConstructorTestingTNewUserUsecaseItf) *UserUsecaseItf {
	mock := &UserUsecaseItf{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
