name: Go

on: [push]

jobs:

  downnload-depenencies:
    name: downnload-depenencies
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

  test:
    name: test
    needs: downnload-depenencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: test
        run: make test